Update openshift.yml

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -186,40 +186,40 @@ jobs:
 
     # The path the image was pushed to is now stored in ${{ steps.push-image.outputs.registry-path }}
 
-    - name: Install oc
-      uses: redhat-actions/openshift-tools-installer@v1
-      with:
-        oc: 4
+    # - name: Install oc
+    #   uses: redhat-actions/openshift-tools-installer@v1
+    #   with:
+    #     oc: 4
 
-    # https://github.com/redhat-actions/oc-login#readme
-    - name: Log in to OpenShift
-      uses: redhat-actions/oc-login@v1
-      with:
-        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
-        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
-        insecure_skip_tls_verify: true
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+    # # https://github.com/redhat-actions/oc-login#readme
+    # - name: Log in to OpenShift
+    #   uses: redhat-actions/oc-login@v1
+    #   with:
+    #     openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+    #     openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+    #     insecure_skip_tls_verify: true
+    #     namespace: ${{ env.OPENSHIFT_NAMESPACE }}
 
-    # This step should create a deployment, service, and route to run your app and expose it to the internet.
-    # https://github.com/redhat-actions/oc-new-app#readme
-    - name: Create and expose app
-      id: deploy-and-expose
-      uses: redhat-actions/oc-new-app@v1
-      with:
-        app_name: ${{ env.APP_NAME }}
-        image: ${{ steps.push-image.outputs.registry-path }}
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-        port: ${{ env.APP_PORT }}
+    # # This step should create a deployment, service, and route to run your app and expose it to the internet.
+    # # https://github.com/redhat-actions/oc-new-app#readme
+    # - name: Create and expose app
+    #   id: deploy-and-expose
+    #   uses: redhat-actions/oc-new-app@v1
+    #   with:
+    #     app_name: ${{ env.APP_NAME }}
+    #     image: ${{ steps.push-image.outputs.registry-path }}
+    #     namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+    #     port: ${{ env.APP_PORT }}
 
-    - name: Print application URL
-      env:
-        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
-      run: |
-        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
-        echo
-        echo "======================== Your application is available at: ========================"
-        echo ${{ env.ROUTE }}
-        echo "==================================================================================="
-        echo
-        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+    # - name: Print application URL
+    #   env:
+    #     ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+    #     SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+    #   run: |
+    #     [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+    #     echo
+    #     echo "======================== Your application is available at: ========================"
+    #     echo ${{ env.ROUTE }}
+    #     echo "==================================================================================="
+    #     echo
+    #     echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
